name: derlung-api

services:
  node-app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - derlung-api-data:/app/data
    restart: unless-stopped

volumes:
  derlung-api-data:
    external: true
